pipeline{
	agent any
  
	stages{
    
		stage( 'clone' ){
		steps{
			git branch:'master' ,url:'https://github.com/likhithaal/Amazon.git'
		    }
  		}
      
		stage( 'clean' ){
		steps{
			dir ('Amazon')
			sh 'mvn clean'
			}
		}
		
		stage( 'test' ){
		steps{
			sh 'mvn test'
			}
		}
		
		stage( 'build' ){
		steps{
			sh 'mvn clean install'
			}
		}
		
	}
}
